services:
  mysqldb:
    container_name: bazaar-mysql
    platform: linux/amd64
    image: mysql:8.0
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bazaar
      - MYSQL_USER=bazaar
      - MYSQL_PASSWORD=bazaar1234
    ports:
      - "3306:3306"
    networks:
      - bazaar-net

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: bazaar-local-redis
    hostname: redis-boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    networks:
      - bazaar-net

  bazaar-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ikhtiyor31/bazaarapi
    restart: always
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
      - redis
    networks:
      - bazaar-net

networks:
  bazaar-net:
    driver: bridge