
== User API

=== SignUp
==== successful case
****
operation::signup[snippets='http-request,request-headers,request-fields,http-response,response-fields']
****

=== SingIn
==== successful case
****
operation::signin[snippets='http-request,request-headers,request-fields,http-response,response-fields']
****

=== Verify Email
==== successful case
****
operation::verify-email[snippets='http-request,request-headers,request-fields,http-response,response-fields']
****

=== Update User Role
==== successful case
****
operation::update-role[snippets='http-request,request-headers,request-fields,http-response,response-fields']
****

=== Refresh Token
==== successful case
****
operation::refreshToken[snippets='http-request,request-headers,request-fields,http-response,response-fields']
****

=== Forgot Password
==== successful case
****
operation::forgot-password[snippets='http-request,request-headers,http-response,response-fields']
****

=== Reset Password
==== successful case
****
operation::reset-password[snippets='http-request,request-headers,request-fields,http-response,response-fields']
****

=== Delete Account
==== successful case
****
operation::delete-account[snippets='http-request,request-headers,http-response']
****

'''